### ISSUE TITLE
locale settings?

### ISSUE THREAD

**Issue by Shura0** [Stypox/dicio-assistance-component#2]
Hi.

How to create skills for different locales? I could not find locale setting in source code.

**Comment by Stypox** [comment]
For some reason I wasn't watching this repo... sorry for answering so late
What do you mean exactly? The skill context passed to skills also contains data about the locale, that can be used by skills to choose what to do. In particular it can be used both at construction time by classes extending `SkillInfo` (so that e.g. the correct `StandardInputRecognizer` compiled sections are chosen when building a skill) and at execution time by all skill components to e.g. send the correct locale to search engines

**Comment by Stypox** [comment]
@Shura0 is my answer clear? In such case I will close the issue

**Comment by Shura0** [comment]
Yes, thank you
